config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :student_group_associations
  resources :student_groups
  resources :resources
  resources :post_threads
  resources :posts
  resources :users
  resources :groups
  resources :mentees
  resources :matches
  resources :mentors
  get 'home/signin', to: 'home#signin', as: :signin
  get 'home/menteedashboard', to: 'home#menteedashboard', as: :menteedashboard
  get 'home/mentordashboard', to: 'home#mentordashboard', as: :mentordashboard
  get 'home/dashboard', to: 'home#dashboard', as: :dashboard
  
  get 'new_mentor', to: 'users#new_mentor', :as => "new_mentor_signup"

  get 'home/public_forum', to: 'home#public_forum', as: :public_forum
  
  get  '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get "sign_up" => "users#new", :as => "sign_up"
  get "/profile", to: "users#index"
  get "home/mentor_matches", to: 'home#mentor_matches', as: :mentormatches
  
  get "home/menteedashboard/photoupload", to: 'users#photo_upload', as: :photo_upload

  root 'home#index'
  

end

app/models/group.rb
class Group < ActiveRecord::Base
  #relationships
  has_many :matches
  has_many :mentors, through: :matches
  has_many :mentees, through: :matches
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:group_name)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :group_name %><br>
    <%= f.text_field :group_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/group_forum.html.erb
<html>

<div class="top-bar foundation-5-top-bar">
  <div id="responsive-menu">
    <div class="top-bar-left">
      <ul class="dropdown vertical medium-horizontal menu" data-responsive-menu="drilldown medium-dropdown" data-auto-height="true" data-animate-height="true">
        <li><strong>CMU CONNECT</strong>&nbsp;
        <li><a href="#">FORUM</a></li>
        <li><a href="#">RESOURCE VAULT</a></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li>Already have an account? </li>
        <%= link_to "Sign In", login_path, class: "button round tiny info" %>
      </ul>
    </div>
  </div>
</div>




<!-- Sample 2-->
<!-- Posts panel container -->
<div class="posts-panel grid">

  <!-- Panel's header -->
  <header class="panel-header">
    <h1 class="panel-title">Group Forum</h1>
  </header>

  <!-- Panel's content -->
  <div class="panel-content">

    <!-- Pinned post section -->
    <section class="pinned-post">
      <!-- Post item -->

      <div class="post-item">

        <!-- Post's thumbnail -->
        <a href="#" class="post-thumbnail">
          <img src="https://static.pexels.com/photos/24587/pexels-photo-24587.jpg" alt="">
        </a>

        <!-- Post's text -->
        <div class="post-text">

          <!-- Post's title -->
          <a href="#">
            <h3 class="post-title">Information Session Next Wednesday</h3>
          </a>
          <div class="post-meta">
            <span class="meta"><span class="meta-icon fa fa-user-circle-o" aria-hidden="true"></span><a class="meta-text">Ryan '16</a></span>
            <span class="meta"><span class="meta-icon fa fa-clock-o" aria-hidden="true"></span><span class="meta-text">11/5/2017 4:30 PM</span></span>
          </div>

          <!-- Post's summary -->
          <div class="post-summary">
            <p>Hey everyone! I will be in town next Wednesday with my company holding an information session for potential full-time job and internship opportunities available.  Please stop by and be sure to bring your resume!
              <a href="#" class="post-read-more">Read more<span class="fa fa-chevron-circle-right" aria-hidden="true"></span></a>
            </p>
          </div>
        </div>
      </div>
    </section>

    <!-- Posts list -->
    <section class="posts-list">
      <div class="post-item">
  
        <div class="post-text">
          <a href="#">
            <h3 class="post-title">Information Session Next Wednesday</h3>
          </a>
          <div class="post-meta">
            <span class="meta"><span class="meta-icon fa fa-user-circle-o" aria-hidden="true"></span><a class="meta-text">Ryan '16</a></span>
            <span class="meta"><span class="meta-icon fa fa-clock-o" aria-hidden="true"></span><span class="meta-text">11/5/2017 4:30 PM</span></span>
          </div>
        </div>
      </div>

      <div class="post-item">

        <div class="post-text">
          <a href="#">
            <h3 class="post-title">Case Interview Preparation?</h3>
          </a>
          <div class="post-meta">
            <span class="meta"><span class="meta-icon fa fa-user-circle-o" aria-hidden="true"></span><a class="meta-text">Jimmy, IS '18</a></span>
            <span class="meta"><span class="meta-icon fa fa-clock-o" aria-hidden="true"></span><span class="meta-text">11/4/2017 9:15 PM</span></span>
          </div>
        </div>
      </div>

      <div class="post-item">

        <div class="post-text">
          <a href="#">
            <h3 class="post-title">Former IS Major In Town</h3>
          </a>
          <div class="post-meta">
            <span class="meta"><span class="meta-icon fa fa-user-circle-o" aria-hidden="true"></span><a class="meta-text">Megan '15</a></span>
            <span class="meta"><span class="meta-icon fa fa-clock-o" aria-hidden="true"></span><span class="meta-text">11/4/2017 11:45 AM</span></span>
          </div>
        </div>
      </div>

      <div class="post-item">

        <div class="post-text">
          <a href="#">
            <h3 class="post-title">What MechE classes should I take junior spring?</h3>
          </a>
          <div class="post-meta">
            <span class="meta"><span class="meta-icon fa fa-user-circle-o" aria-hidden="true"></span><a class="meta-text">Nicole MechE '19</a></span>
            <span class="meta"><span class="meta-icon fa fa-clock-o" aria-hidden="true"></span><span class="meta-text">11/4/2017 10:50 AM</span></span>
          </div>
        </div>
      </div>
    </section>
  </div>
</div>


<div class="status-update-input-box">
  <form>
    <div class="row input-box-container">
      <div class="columns">
        <label> <!-- Add a Label here to give this input box a heading -->
          <textarea rows="5" placeholder="New Post"></textarea>
        </label>
      </div>
    </div>
    <div class="row medium-collapse user-action-container">
      <div class="small-12 medium-7 columns">

        </div>
      </div>
      <div class="small-12 medium-5 columns">
        <div class="user-submit-box">
          <input type="submit" class="button small" value="POST">
        </div>
      </div>
    </div>
  </form>
</div>



</html>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Groups</h1>

<table>
  <thead>
    <tr>
      <th>Group name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.group_name %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Group name:</strong>
  <%= @group.group_name %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>