config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :student_group_associations
  resources :student_groups
  resources :resources
  resources :post_threads
  resources :posts
  resources :users
  resources :groups
  resources :mentees
  resources :matches
  resources :mentors
  get 'home/signin', to: 'home#signin', as: :signin
  get 'home/menteedashboard', to: 'home#menteedashboard', as: :menteedashboard
  get 'home/mentordashboard', to: 'home#mentordashboard', as: :mentordashboard
  get 'home/dashboard', to: 'home#dashboard', as: :dashboard
  
  get 'new_mentor', to: 'users#new_mentor', :as => "new_mentor_signup"

  get 'home/public_forum', to: 'home#public_forum', as: :public_forum
  
  get  '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get "sign_up" => "users#new", :as => "sign_up"
  get "/profile", to: "users#index"
  get "home/mentor_matches", to: 'home#mentor_matches', as: :mentormatches
  
  get "home/menteedashboard/photoupload", to: 'users#photo_upload', as: :photo_upload

  root 'home#index'
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/dashboard.html.erb
<% if current_user.user_type == 'Mentor'  %>
  <script type="text/javascript">
    window.location.href="mentordashboard"  // put your correct path in a string here
  </script>
<% else %>
  <script type="text/javascript">
    window.location.href="menteedashboard"  // put your correct path in a string here
  </script>
<% end %>

app/views/home/index.html.erb
<html>

</br></br>
<div class="work-feature-block row">
	<h4 class="work-feature-block-header">Connect with a mentor today!</h4></br>
  <div class="columns medium-7">
  </br>
    <img class="work-feature-block-image" <%= image_tag 'home.jpg' %>
  </div>
  <div class="columns medium-5">
    <div class="login-box">
  <div class="row collapse expanded">
    <div class="small-12 medium-6 column small-order-2 medium-order-1">
        <center><h1 class="login-box-title">Sign up now!</h1></center>
        <center><h5>Sign up as a</h5></center></br>
        <%= link_to "Student", sign_up_path, :class => "button primary round expanded" %>
    	 <center><h5>OR</h5></center>
        <%= link_to "Alum", new_mentor_signup_path, :class => "button alert round expanded" %>
         </br><center><p class="form-registration-member-signin">Already a member? <%= link_to "Sign In", login_path%></p></center>
    	 <center><p class="form-registration-terms"><a href="#">Terms &amp; Conditions</a>|<a href="#">Privacy</a></p></center>

    </div>
  </div>
</div>


  </div>
</div>
</html>

app/views/home/menteedashboard.html.erb
 
<br></br>

 	 <%# if !current_user.image_filename.nil? %>
 	     <p><%#= image_tag current_user.image_filename %></p>
 	   <%# end %>
	   
	   

<div class="portfolio-resume row">

  <div class="large-4 columns">
    <div class="portfolio-resume-wrapper">
	<% if current_user.image_filename.nil? %>
		<img class="portfolio-resume-headshot" src="https://placehold.it/250" alt="headshot">
	<% else %>
		<%= image_tag current_user.image_filename ,:class=> "img-circular" %>
	<% end %>
<!-- use button tag for on page actions -->
	  <br></br>
<button class="button primary round">Edit Profile</button>
<br></br>
<%= link_to "Upload Photo", photo_upload_path, :class => "button primary round" %>
<br></br>
<button class="button primary round">Access Guidebook</button>



    </div>
  </div>

  <div class="large-4 columns">
    <div class="portfolio-resume-wrapper">
      <h3 class="portfolio-resume-header">Welcome <%= current_user.first_name %>!</h3>
      <div class="portfolio-resume-spacing">
        <p>Name: <%= current_user.first_name %> <%= current_user.last_name %></p>
        <p>Email: <%= current_user.email %> </p>
		<p>Major: <%= current_user.major %> </p>
		<p>Graudation Year: <%= current_user.mentee.expected_graduation %> </p>
      </div>
    </div>
  </div>

  <div class="large-4 columns">
	  <% match = Match.all.select {|n| n if n.mentee_id == current_user.mentee.id} %>
	  <% if !match.empty? %>
    <div class="portfolio-resume-wrapper">
	  
	  <div class="card profile-card-action-icons">
	    <div class="card-section">
	      <div class="profile-card-header">
	        <div class="profile-card-avatar">
	          <img class="avatar-image" src="https://pbs.twimg.com/profile_images/732634911761260544/OxHbNdTF.jpg" alt="Harry Manchanda">
	        </div>
	        <div class="profile-card-author">
				
	          <h5 class="author-title"><%= User.find(Mentor.find(match.first.mentor_id).user_id).first_name %> <%= User.find(Mentor.find(match.first.mentor_id).user_id).last_name %> </h5>
	          <p class="author-description"><%= Mentor.find(match.first.mentor_id).job_title %>, <%= Mentor.find(match.first.mentor_id).company %></p>
	        </div>
	      </div>
	      <div class="profile-card-about">
	        <h5 class="about-title separator-left">Mentor</h5>
	        <p class="about-content">
	          Email:  <%= User.find(Mentor.find(match.first.mentor_id).user_id).email %> <br></br>
			  Major: <%= User.find(Mentor.find(match.first.mentor_id).user_id).major %> <br></br>
			  Class of <%= Mentor.find(match.first.mentor_id).graduation %> <br></br>
	        </p>
	      </div>
	      <div class="profile-card-action">
			  <%= link_to "View Profile", User.find(Mentor.find(match.first.mentor_id).user_id), :class => "button primary round expanded" %>




	      </div>
	    </div>
	  </div>
	 <% end %>
	 



    </div>
  </div>

</div>

app/views/home/mentor_matches.html.erb
<% mentor_matches = Match.all.select {|n| n if n.mentor_id == current_user.mentor.id} %>
<% if !mentor_matches.empty? %>

<div class="people-you-might-know">
  <div class="add-people-header">
    <h6 class="header-title">
      Matches
    </h6>
  </div>

<% mentor_matches.each do |match| %>
  <div class="row add-people-section">
    <div class="small-12 medium-6 columns about-people">
      <div class="about-people-avatar">
        <img class="avatar-image" src="https://pbs.twimg.com/profile_images/732634911761260544/OxHbNdTF.jpg" alt="Kishore Kumar">
      </div>
      <div class="about-people-author">
        <p class="author-name">
          <%= User.find(Mentee.find(match.mentee_id).user_id).first_name %> <%= User.find(Mentee.find(match.mentee_id).user_id).last_name %>
        </p>
        <p class="author-location">
          <i class="fa fa-map-marker" aria-hidden="true"></i>
          <%= User.find(Mentee.find(match.mentee_id).user_id).major %>, <%= Mentee.find(match.mentee_id).expected_graduation %>
        </p>
      </div>    
    </div>
    <div class="small-12 medium-6 columns add-friend">
      <div class="add-friend-action">
        <%= link_to "View Profile", User.find(Mentee.find(match.mentee_id).user_id), :class => "button primary round" %>
      </div>
    </div>
  </div>
  <% end %>

</div>
<% end %>

app/views/home/mentordashboard.html.erb
 
<br></br>

<div class="portfolio-resume row">

  <div class="large-4 columns">
    <div class="portfolio-resume-wrapper">
		<% if current_user.image_filename.nil? %>
			<img class="portfolio-resume-headshot" src="https://placehold.it/250" alt="headshot">
		<% else %>
			<%= image_tag current_user.image_filename ,:class=> "img-circular" %>
		<% end %>

<!-- use button tag for on page actions -->
	  <br></br>
<button class="button button-rounded-hover">Edit Profile</button>
<br></br>
<button class="button button-rounded-hover">Upload Resume</button>
<br></br>
<button class="button button-rounded-hover">Upload to Guidebook</button>



    </div>
  </div>

  <div class="large-4 columns">
    <div class="portfolio-resume-wrapper">
      <h3 class="portfolio-resume-header">Welcome <%= current_user.first_name %>!</h3>
      <div class="portfolio-resume-spacing">
        <p>Name: <%= current_user.first_name %> <%= current_user.last_name %></p>
        <p>Email: <%= current_user.email %> </p>
		<p>Major: <%= current_user.major %> </p>
		<p>Graudation Year: <%= current_user.mentor.graduation %> </p>
      </div>
    </div>
  </div>
  
  

  <div class="large-4 columns">
	  <!-- edit when logout functionality works -->
	  <% match = Match.all.select {|n| n if n.mentor_id == current_user.mentor.id} %>
	  <% if !match.empty? %>
    <div class="portfolio-resume-wrapper">
	  
	  <div class="card profile-card-action-icons">
	    <div class="card-section">
	      <div class="profile-card-header">
	        <div class="profile-card-avatar">
	          <img class="avatar-image" src="https://pbs.twimg.com/profile_images/732634911761260544/OxHbNdTF.jpg" alt="Harry Manchanda">
	        </div>
	        <div class="profile-card-author">
				
	          <h5 class="author-title"><%= User.find(Mentee.find(match.last.mentee_id).user_id).first_name %> <%= User.find(Mentee.find(match.last.mentee_id).user_id).last_name %> </h5>
	          <p class="author-description"><%= User.find(Mentee.find(match.last.mentee_id).user_id).major %>, <%= Mentee.find(match.last.mentee_id).expected_graduation %></p>
	        </div>
	      </div>
	      <div class="profile-card-about">
	        <h5 class="about-title separator-left">Most Recent Match</h5>
	        <p class="about-content">
	          Email:  <%= User.find(Mentee.find(match.last.mentee_id).user_id).email %> <br></br>
			  Home State: <%= User.find(Mentee.find(match.last.mentee_id).user_id).home_state %> <br></br>
			  Preferred Industry: <%= Mentee.find(match.last.mentee_id).preferred_industry %> <br></br>
	        </p>
	      </div>
	      <div class="profile-card-action">
			  <%= link_to "View Profile", User.find(Mentee.find(match.last.mentee_id).user_id), :class => "button primary round expanded" %>




	      </div>
	    </div>
	  </div>
	 <% end %>
<%= link_to "View All Matches", mentormatches_path, :class => "button primary round" %>
<%= link_to "Change Number of Matches", edit_user_path(current_user), :class => "button primary round" %>
	  

    </div>
  </div>

</div>

app/views/home/public_forum.html.erb
<!-- Sample 2-->
<!-- Posts panel container -->
<div class="posts-panel grid">

  <!-- Panel's header -->
  <header class="panel-header">
    <h1 class="panel-title">Public Forum</h1>
  </header>

  <!-- Panel's content -->
  <div class="panel-content">

    <!-- Pinned post section -->
    <section class="pinned-post">
      <!-- Post item -->

      <div class="post-item">

        <!-- Post's thumbnail -->
        <a href="#" class="post-thumbnail">
          <img src="https://static.pexels.com/photos/24587/pexels-photo-24587.jpg" alt="">
        </a>

        <!-- Post's text -->
        <div class="post-text">

          <!-- Post's title -->
          <a href="#">
            <h3 class="post-title">Information Session Next Wednesday</h3>
          </a>
          <div class="post-meta">
            <span class="meta"><span class="meta-icon fa fa-user-circle-o" aria-hidden="true"></span><a class="meta-text">Ryan '16</a></span>
            <span class="meta"><span class="meta-icon fa fa-clock-o" aria-hidden="true"></span><span class="meta-text">11/5/2017 4:30 PM</span></span>
          </div>

          <!-- Post's summary -->
          <div class="post-summary">
            <p>Hey everyone! I will be in town next Wednesday with my company holding an information session for potential full-time job and internship opportunities available.  Please stop by and be sure to bring your resume!
              <a href="#" class="post-read-more">Read more<span class="fa fa-chevron-circle-right" aria-hidden="true"></span></a>
            </p>
          </div>
        </div>
      </div>
    </section>

    <!-- Posts list -->
    <section class="posts-list">
      <div class="post-item">
  
        <div class="post-text">
          <a href="#">
            <h3 class="post-title">Information Session Next Wednesday</h3>
          </a>
          <div class="post-meta">
            <span class="meta"><span class="meta-icon fa fa-user-circle-o" aria-hidden="true"></span><a class="meta-text">Ryan '16</a></span>
            <span class="meta"><span class="meta-icon fa fa-clock-o" aria-hidden="true"></span><span class="meta-text">11/5/2017 4:30 PM</span></span>
          </div>
        </div>
      </div>

      <div class="post-item">

        <div class="post-text">
          <a href="#">
            <h3 class="post-title">Case Interview Preparation?</h3>
          </a>
          <div class="post-meta">
            <span class="meta"><span class="meta-icon fa fa-user-circle-o" aria-hidden="true"></span><a class="meta-text">Jimmy, IS '18</a></span>
            <span class="meta"><span class="meta-icon fa fa-clock-o" aria-hidden="true"></span><span class="meta-text">11/4/2017 9:15 PM</span></span>
          </div>
        </div>
      </div>

      <div class="post-item">

        <div class="post-text">
          <a href="#">
            <h3 class="post-title">Former IS Major In Town</h3>
          </a>
          <div class="post-meta">
            <span class="meta"><span class="meta-icon fa fa-user-circle-o" aria-hidden="true"></span><a class="meta-text">Megan '15</a></span>
            <span class="meta"><span class="meta-icon fa fa-clock-o" aria-hidden="true"></span><span class="meta-text">11/4/2017 11:45 AM</span></span>
          </div>
        </div>
      </div>

      <div class="post-item">

        <div class="post-text">
          <a href="#">
            <h3 class="post-title">What MechE classes should I take junior spring?</h3>
          </a>
          <div class="post-meta">
            <span class="meta"><span class="meta-icon fa fa-user-circle-o" aria-hidden="true"></span><a class="meta-text">Nicole MechE '19</a></span>
            <span class="meta"><span class="meta-icon fa fa-clock-o" aria-hidden="true"></span><span class="meta-text">11/4/2017 10:50 AM</span></span>
          </div>
        </div>
      </div>
    </section>
  </div>
</div>


<div class="status-update-input-box">
  <form>
    <div class="row input-box-container">
      <div class="columns">
        <label> <!-- Add a Label here to give this input box a heading -->
          <textarea rows="5" placeholder="New Post"></textarea>
        </label>
      </div>
    </div>
    <div class="row medium-collapse user-action-container">
      <div class="small-12 medium-7 columns">

        </div>
      </div>
      <div class="small-12 medium-5 columns">
        <div class="user-submit-box">
          <input type="submit" class="button small" value="POST">
        </div>
      </div>
    </div>
  </form>
</div>



</html>

app/views/home/signin.html.erb
<form>
<div class="center">
<div class="medium-4 columns">
  <div class="sign-in-form">
    <h4 class="text-center">Sign In</h4>
    <label for="sign-in-form-username">Username</label>
    <input type="text" class="sign-in-form-username" id="sign-in-form-username">
    <label for="sign-in-form-password">Password</label>
    <input type="text" class="sign-in-form-password" id="sign-in-form-password">
    <button type="submit" class="sign-in-form-button">Sign In</button>
  </div>
</div>
</div>
</form>