config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :student_group_associations
  resources :student_groups
  resources :resources
  resources :post_threads
  resources :posts
  resources :users
  resources :groups
  resources :mentees
  resources :matches
  resources :mentors
  get 'home/signin', to: 'home#signin', as: :signin
  get 'home/menteedashboard', to: 'home#menteedashboard', as: :menteedashboard
  get 'home/mentordashboard', to: 'home#mentordashboard', as: :mentordashboard
  get 'home/dashboard', to: 'home#dashboard', as: :dashboard
  
  get 'new_mentor', to: 'users#new_mentor', :as => "new_mentor_signup"

  get 'home/public_forum', to: 'home#public_forum', as: :public_forum
  
  get  '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get "sign_up" => "users#new", :as => "sign_up"
  get "/profile", to: "users#index"
  get "home/mentor_matches", to: 'home#mentor_matches', as: :mentormatches
  
  get "home/menteedashboard/photoupload", to: 'users#photo_upload', as: :photo_upload

  root 'home#index'
  

end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :resource_type %><br>
    <%= f.text_field :resource_type %>
  </div>
  <div class="field">
    <%= f.label :resource_name %><br>
    <%= f.text_field :resource_name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Resources</h1>

<table>
  <thead>
    <tr>
      <th>Resource type</th>
      <th>Resource name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.resource_type %></td>
        <td><%= resource.resource_name %></td>
        <td><%= resource.user_id %></td>
        <td><%= link_to 'Show', resource %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1>New Resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Resource type:</strong>
  <%= @resource.resource_type %>
</p>

<p>
  <strong>Resource name:</strong>
  <%= @resource.resource_name %>
</p>

<p>
  <strong>User:</strong>
  <%= @resource.user_id %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>