config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :student_group_associations
  resources :student_groups
  resources :resources
  resources :post_threads
  resources :posts
  resources :users
  resources :groups
  resources :mentees
  resources :matches
  resources :mentors
  get 'home/signin', to: 'home#signin', as: :signin
  get 'home/menteedashboard', to: 'home#menteedashboard', as: :menteedashboard
  get 'home/mentordashboard', to: 'home#mentordashboard', as: :mentordashboard
  get 'home/dashboard', to: 'home#dashboard', as: :dashboard
  
  get 'new_mentor', to: 'users#new_mentor', :as => "new_mentor_signup"

  get 'home/public_forum', to: 'home#public_forum', as: :public_forum
  
  get  '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get "sign_up" => "users#new", :as => "sign_up"
  get "/profile", to: "users#index"
  get "home/mentor_matches", to: 'home#mentor_matches', as: :mentormatches
  
  get "home/menteedashboard/photoupload", to: 'users#photo_upload', as: :photo_upload

  root 'home#index'
  

end

app/models/match.rb
class Match < ActiveRecord::Base
  include SessionsHelper
  #relationpships
  belongs_to :mentor
  has_one :mentee
  belongs_to :group
  
  def generate_match
    puts "current_user"
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all
  end
  
  def generate_match
    puts "generate match"
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:mentor_id, :mentee_id, :active, :group_id)
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mentor_id %><br>
    <%= f.number_field :mentor_id %>
  </div>
  <div class="field">
    <%= f.label :mentee_id %><br>
    <%= f.number_field :mentee_id %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :group_id %><br>
    <%= f.number_field :group_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form' %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Matches</h1>


<table>
  <thead>
    <tr>
      <th>Mentor</th>
      <th>Mentee</th>
      <th>Active</th>
      <th>Group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td><%= match.mentor_id %></td>
        <td><%= match.mentee_id %></td>
        <td><%= match.active %></td>
        <td><%= match.group_id %></td>
        <td><%= link_to 'Show', match %></td>
        <td><%= link_to 'Edit', edit_match_path(match) %></td>
        <td><%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Match', new_match_path %>

app/views/matches/new.html.erb
<h1>New Match</h1>

<%= render 'form' %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mentor:</strong>
  <%= @match.mentor_id %>
</p>

<p>
  <strong>Mentee:</strong>
  <%= @match.mentee_id %>
</p>

<p>
  <strong>Active:</strong>
  <%= @match.active %>
</p>

<p>
  <strong>Group:</strong>
  <%= @match.group_id %>
</p>

	

<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>